MyAero/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import MyAero.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^about/', MyAero.views.about_page),
    url(r'^articles/', include('article.urls')),
    url(r'^book/', include('booking.urls')),
    url(r'^', MyAero.views.home_page),
]

booking/urls.py
from django.conf.urls import url
from django.contrib import admin

import booking.views

urlpatterns = [
    url(r'^state_out_ajax/$', booking.views.state_out_ajax, name='state_out_ajax'),
    url(r'^city_out_ajax/$', booking.views.city_out_ajax, name='city_out_ajax'),
    url(r'^state_in_ajax/$', booking.views.state_in_ajax, name='state_in_ajax'),
    url(r'^city_in_ajax/$', booking.views.city_in_ajax, name='city_in_ajax'),
    url(r'^success/$', booking.views.success),
    url(r'^', booking.views.add_booker),
]

booking/models.py
from datetime import date
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class State(models.Model):
    name = models.CharField(max_length=30)
    country = models.ForeignKey(Country)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=30)
    state = models.ForeignKey(State)

    def __str__(self):
        return self.name


class Booking(models.Model):
    class Meta():
        db_table = 'booking'

    firstname = models.CharField(max_length=20)
    surname = models.CharField(max_length=30)
    email = models.EmailField(default="")
    date_out = models.DateField(default=date.today)
    date_in = models.DateField(default=date.today)
    country_out = models.CharField(default="", max_length=30)
    country_in = models.CharField(default="", max_length=30)
    state_out = models.CharField(default="", max_length=30)
    state_in = models.CharField(default="", max_length=30)
    city_out = models.CharField(default="", max_length=30)
    city_in = models.CharField(default="", max_length=30)

booking/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget

from booking.models import Booking, Country, State, City


class BookForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['firstname', 'surname', 'email', 'date_in', 'date_out', 'country_out', 'country_in', 'state_out',
                  'state_in', 'city_out', 'city_in']

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields['date_in'] = forms.DateField(widget=AdminDateWidget)
        self.fields['date_out'] = forms.DateField(widget=AdminDateWidget)
        self.fields['country_out'] = forms.ModelChoiceField(queryset=Country.objects.all())
        self.fields['country_in'] = forms.ModelChoiceField(queryset=Country.objects.all())
        self.fields['state_out'] = forms.ModelChoiceField(queryset=State.objects.filter(id=0))
        self.fields['state_in'] = forms.ModelChoiceField(queryset=State.objects.filter(id=0))
        self.fields['city_out'] = forms.ModelChoiceField(queryset=City.objects.filter(id=0))
        self.fields['city_in'] = forms.ModelChoiceField(queryset=City.objects.filter(id=0))

booking/views.py
# coding=utf-8
import json

from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, render_to_response
from django.contrib import auth
from booking.forms import BookForm
from booking.models import State, City, Country



def success(request):
    return render_to_response('success.html', {'username': auth.get_user(request).username})


def add_booker(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        #if form.is_valid():
        #email = form.cleaned_data['email']
        email = request.POST['email']

        countryout = Country.objects.get(pk=request.POST['country_out'])
        countryin = Country.objects.get(pk=request.POST['country_in'])
        stateout = State.objects.get(pk=request.POST['state_out'])
        statein = State.objects.get(pk=request.POST['state_in'])
        cityout = City.objects.get(pk=request.POST['city_out'])
        cityin = City.objects.get(pk=request.POST['city_in'])

        subject = u"Your Ticket Order. We will contact with you!"
        message = u"Name: %s" % request.POST['firstname']
        message += u"\nSurname: %s" % request.POST['surname']
        message += u"\nDate out: %s" % request.POST['date_in']
        message += u"\nDate in: %s" % request.POST['date_out']
        message += u"\nCountry out: %s" % countryout
        message += u"\nState out: %s" % stateout
        message += u"\nCity out: %s" % cityout
        message += u"\nCountry in: %s" % countryin
        message += u"\nState in: %s" % statein
        message += u"\nCity in: %s" % cityin

        from_email = settings.EMAIL_HOST_USER
        to_list = [email, settings.EMAIL_HOST_USER]
        send_mail(subject, message, from_email, to_list, fail_silently=True)
        #form.save()
        return HttpResponseRedirect('../success/')
    else:
        form = BookForm()

    return render(request, 'booking.html', {'form': form, 'username': auth.get_user(request).username,})


def state_out_ajax(request):
    if request.POST and request.is_ajax():
        c_id = request.POST.get('country_id')
        state = State.objects.filter(country_id=c_id)
        state_dict = {}
        for state in state:
            state_dict[state.id] = state.name
        print state_dict, json.dumps(state_dict)
        return JsonResponse(state_dict, content_type="application/json")  # shortcut for json.dumps


def city_out_ajax(request):
    if request.POST and request.is_ajax():
        s_id = request.POST.get('state_id')
        city = City.objects.filter(state_id=s_id)
        city_dict = {}
        for city in city:
            city_dict[city.id] = city.name
        return HttpResponse(json.dumps(city_dict), content_type="application/json")


def state_in_ajax(request):
    if request.POST and request.is_ajax():
        c_id = request.POST.get('country_id')
        state = State.objects.filter(country_id=c_id)
        state_dict = {}
        for state in state:
            state_dict[state.id] = state.name
        print state_dict, json.dumps(state_dict)
        return JsonResponse(state_dict, content_type="application/json")  # shortcut for json.dumps


def city_in_ajax(request):
    if request.POST and request.is_ajax():
        s_id = request.POST.get('state_id')
        city = City.objects.filter(state_id=s_id)
        city_dict = {}
        for city in city:
            city_dict[city.id] = city.name
        return HttpResponse(json.dumps(city_dict), content_type="application/json")

booking/templates/booking.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>AirLines</title>
		<meta charset="utf-8">

        <link href="{% static 'admin/css/forms.css' %}" type="text/css" media="all" rel="stylesheet" />
        <link href="{% static 'admin/css/widgets.css' %}" type="text/css" media="all" rel="stylesheet" />

        <link rel="stylesheet" href="{% static "static/css/style.css" %}" type="text/css" media="all">
		<link rel="shortcut icon" href="{% static 'static/images/logotitle.png' %}" />

        <script type="text/javascript" src="/admin/jsi18n/"></script>
        <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
        <script type="text/javascript" src="{% static 'admin/js/calendar.js' %}"></script>
        <script type="text/javascript" src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>
        <script type="text/javascript" src="{% static 'static/js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
        <script type="text/javascript" src="{% static 'static/js/ajax.jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'static/js/formvalidation.js' %}"></script>

        <script type="text/javascript">
            $(document).ready(function(){
               $("#id_country_out").change(function(){
                  console.log('works');
                  $.ajax({
                    url : "{% url 'state_out_ajax' %}",
                    type : "POST",
                    data : {
                      csrfmiddlewaretoken : "{{ csrf_token }}",
                      country_id : $("#id_country_out").val()
                      },

                    dataType : 'json',

                    success : function(data){
                        $("#id_state_out").empty().append('<option>Select Region</option>');
                        $("#id_city_out").empty().append('<option>Select City</option>');
                        $.each(data, function(key, value){
                            $("#id_state_out").append('<option value=" ' +key+' ">'+ value +'</option>');
                          });

                          $("#id_state_out").change(function(){
                            console.log('works');
                            $.ajax({
                          url : "{% url 'city_out_ajax' %}",
                              type : "POST",
                              data : {
                                  csrfmiddlewaretoken : "{{ csrf_token }}",
                                  state_id : $("#id_state_out").val()
                                },

                              dataType : 'json',

                              success : function(data){
                            $("#id_city_out").empty();
                                  $.each(data, function(key, value){
                                    $("#id_city_out").append('<option value=" '+key+' ">'+ value +'</option>');
                                  });
                                  console.log(data);
                            },
                              error : function(){
                                  console.log(arguments);
                            }
                          });
                        });

                    },
                      error : function(){
                        console.log(arguments);
                    }
                  });
                });
            });

        </script>

        <script type="text/javascript">
            $(document).ready(function(){
               $("#id_country_in").change(function(){
                  console.log('works');
                  $.ajax({
                    url : "{% url 'state_in_ajax' %}",
                    type : "POST",
                    data : {
                      csrfmiddlewaretoken : "{{ csrf_token }}",
                      country_id : $("#id_country_in").val()
                      },

                    dataType : 'json',

                    success : function(data){
                        $("#id_state_in").empty().append('<option>Select Region</option>');
                        $("#id_city_in").empty().append('<option>Select City</option>');
                        $.each(data, function(key, value){
                            $("#id_state_in").append('<option value=" ' +key+' ">'+ value +'</option>');
                          });

                          $("#id_state_in").change(function(){
                            console.log('works');
                            $.ajax({
                          url : "{% url 'city_in_ajax' %}",
                              type : "POST",
                              data : {
                                  csrfmiddlewaretoken : "{{ csrf_token }}",
                                  state_id : $("#id_state_in").val()
                                },

                              dataType : 'json',

                              success : function(data){
                            $("#id_city_in").empty();
                                  $.each(data, function(key, value){
                                    $("#id_city_in").append('<option value=" '+key+' ">'+ value +'</option>');
                                  });
                                  console.log(data);
                            },
                              error : function(){
                                  console.log(arguments);
                            }
                          });
                        });

                    },
                      error : function(){
                        console.log(arguments);
                    }
                  });
                });
            });


        </script>
	</head>
	<body id="page1">
		<div class="main">
			<header>
				<div class="wrapper">
					<h1><a href="../home/" id="logo">AirLines</a></h1>
					<nav id="top_nav">
                        <section class="top-bar-section">
                            <ul class="right">
            {% if username %}
                <li><a href="/auth/logout/">Log out ({{ username }})</a></li>
            {% else %}
                <li><a href="/auth/login/">Sign in</a></li>
            {% endif %}
                            </ul>
                        </section>
					</nav>
				</div>
				<nav>
					<ul id="menu">
                        <li><a href="../home/"><span><span>Home</span></span></a></li>
                        <li id="menu_active"><a href="../book/"><span><span>Book</span></span></a></li>
                        <li><a href="../articles/"><span><span>Comments</span></span></a></li>
                        <li><a href="../about/"><span><span>About</span></span></a></li>
                    </ul>
				</nav>
			</header>
			<!-- / header -->
			<!--content -->
        <section id="content">
            {% if username %}
                <div class="booking">
                    <form method="post" action="/book/send/" onsubmit="return validate_form(this)">
                        {% csrf_token %}
                        <table>
                            <tr>
                                <td class="td_button" colspan="2">
                                    <h2>Order Tickets</h2>
                                </td>
                            </tr>
                            <tr>
                                <tr>
                                <td class="td_user" colspan="2">First name:
                                    {{ form.firstname }}
                                </td>
                                </tr>
                                <tr>
                                <td class="td_user" colspan="2">Last name:
                                    {{ form.surname }}
                                </td>

                                </tr>
                                <tr>
                                <td class="td_user" colspan="2">Email:
                                    {{ form.email }}
                                </td>
                                </tr>
                            </tr>
                            <tr>
                                <td class="td_left"><b>From whence:</b>
                                    <div>
                                        <div>Country</div>
                                        {{ form.country_out }}
                                    </div>
                                    <div>
                                        <div>Region</div>
                                        {{ form.state_out }}
                                    </div>

                                    <div>
                                    <div>City</div>
                                        {{ form.city_out }}
                                    </div>
                                </td>

                                <td class="td_center"><b>To where:</b>
                                    <div>
                                        <div>Country</div>
                                        {{ form.country_in }}
                                    </div>
                                    <div>
                                        <div>Region</div>
                                        {{ form.state_in }}
                                    </div>

                                    <div>
                                    <div>City</div>
                                        {{ form.city_in }}
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="td_left">Leaving:<br>
                                    {{ form.date_out }}
                                </td>
                                <td class="td_center">Return:<br>
                                    {{ form.date_in }}
                                </td>

                            </tr>

                            <tr>
                                <td class="td_button" colspan="2">
                                    <input class="ordersubmit" type="submit" name="submit" value="Order" />
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            {% else %}
                <div class="no_book">
                    <b>To order tickets need <a href="/auth/login/">Sign in</a></b>
                </div>
            {% endif %}
        </section>
			<!--content end-->
			<!--footer -->
			<footer>
				<div class="wrapper">
					<div class="links">Copyright &copy; <a href="#">A&N</a> All Rights Reserved<br>
					Design by <a href="http://www.vk.com/gaponenko_anton">Anton</a> and <a href="http://www.vk.com/nazarskiy">Nazar</a></div>
				</div>
			</footer>
		</div>
	</body>
</html>

booking/templates/success.html
{% extends 'base.html' %}
{% block menu%}
    <ul id="menu">
        <li><a href="\home/"><span><span>Home</span></span></a></li>
        <li><a href="\book/"><span><span>Book</span></span></a></li>
        <li><a href="\comments/"><span><span>Comments</span></span></a></li>
        <li><a href="\about/"><span><span>About</span></span></a></li>
    </ul>
{% endblock %}


{% block content %}

    <section id="content">
            <div class="no_book">
             <b>Thank you for your order!<br><br>We will connect with you in nearest time!<br><br>To leave a feedback go to <a href="\articles/">Comments</a></b>
            </div>
     </section>


{% endblock %}